version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - sudo mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - mkdir $ANDROID_HOME/licenses
      - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
      - android update sdk --no-ui --filter build-tools-24.4.1,android-24,extra-android-m2repository
      - yes | sudo sdkmanager --licenses
      
  build:
    commands:
      - ./gradlew assembleDebug --stacktrace 
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
